import { extendAdmin } from '@bias/admin'

const PAGE_KEY = 'tags.index'

export function buildTagsPageExtender() {
  return extendAdmin(admin => admin
    .pageCopy(PAGE_KEY, {
  key: 'tags-page-copy',
  order: 10,
  resolve: () => ({
    pageTitle: '标签管理',
    pageDescription: '管理讨论标签和分类',
    createLabel: '创建标签',
    refreshLabel: '刷新统计',
    refreshingLabel: '刷新中...',
    loadingText: '加载中...',
    emptyText: '暂无标签',
    previewLabel: '实时预览',
    previewRootText: '当前会作为顶级标签显示在列表中。',
    previewChildText: '当前会作为子标签显示在父标签下方。',
    previewFallbackName: '新标签',
    modalCreateTitle: '创建标签',
    modalEditTitle: '编辑标签',
    modalSubtitle: '配置父子层级、排序和显示状态。',
    tablePreviewHeader: '预览',
    tableNameHeader: '标签名称',
    tableSlugHeader: '别名',
    tableHierarchyHeader: '层级',
    tableStatusHeader: '状态',
    tableDiscussionCountHeader: '讨论数',
    tableActionHeader: '操作',
    nameLabel: '标签名称 *',
    namePlaceholder: '例如：技术讨论',
    slugLabel: '别名 / Slug',
    slugPlaceholder: '例如：tech-talk',
    slugHelpText: '留空时自动生成，建议使用短横线风格。',
    descriptionLabel: '描述',
    descriptionPlaceholder: '标签的简短描述',
    parentLabel: '父标签',
    parentRootOptionLabel: '作为顶级标签',
    parentHelpText: '只能选择顶级标签作为父标签；设置后，这个标签会显示在对应父标签下方。',
    parentChildrenBlockedText: '当前标签下已有子标签，不能再把它设为次标签。',
    positionLabel: '排序位置',
    positionPlaceholder: '0',
    positionHelpTextPrefix: '数字越小越靠前',
    positionHelpRootText: '顶级标签层',
    positionHelpParentText: '当前父标签下',
    colorLabel: '颜色',
    colorPlaceholder: '#888888',
    colorPickerAriaLabel: '标签颜色选择器',
    iconLabel: '图标',
    clearIconLabel: '清除图标',
    iconSearchPlaceholder: '搜索图标，例如 code、comments、tag',
    iconNoMatchText: '没有找到匹配的图标',
    iconHelpText: '标签仍然保存为 Font Awesome 类名，但现在可以直接搜索和点选。',
    iconManualLabel: '手动输入图标类名',
    iconManualPlaceholder: '高级模式：手动输入 Font Awesome 类名',
    visibilityLabel: '显示与发帖限制',
    hiddenLabel: '隐藏标签',
    restrictedLabel: '限制发帖',
    viewScopeLabel: '查看权限',
    startScopeLabel: '发帖权限',
    replyScopeLabel: '回帖权限',
    startScopeHelpText: '发帖权限不能比查看权限更宽松。',
    restrictedHelpText: '“限制发帖”开启后，普通用户无法在该标签下发起讨论；回帖权限仍按这里的配置生效。',
    postingHelpText: '标签级权限会作用到讨论列表、详情页、发帖和回帖流程。',
    editLabel: '编辑',
    moveUpLabel: '上移',
    moveDownLabel: '下移',
    deleteLabel: '删除',
    saveLabel: '保存',
    savingLabel: '保存中...',
    cancelLabel: '取消',
    tagPreviewCardLabel: '实时预览',
    tagPreviewRootText: '当前会作为顶级标签显示在列表中。',
    tagPreviewChildText: '当前会作为子标签显示在父标签下方。',
    sortTextPrefix: '排序',
    rootLevelText: '顶级标签',
    childLevelText: '子标签',
    childOwnedPrefix: '隶属',
    viewTextPrefix: '查看',
    startTextPrefix: '发帖',
    replyTextPrefix: '回帖',
    publicText: '公开',
    summaryTagTotalLabel: '标签总数',
    summaryTagHierarchyLabel: '顶级 / 子标签',
    summaryHiddenLabel: '隐藏标签',
    summaryRestrictedLabel: '限制发帖',
    configHierarchyLabel: '层级',
    configSortLabel: '排序',
    configViewLabel: '查看范围',
    configPostingLabel: '发帖 / 回帖',
  }),
})
    .pageConfig(PAGE_KEY, {
  key: 'tags-page-config',
  order: 10,
  resolve: () => ({
    colorPresets: [
      '#3c78d8',
      '#4d698e',
      '#0e7490',
      '#0f766e',
      '#2f855a',
      '#65a30d',
      '#ca8a04',
      '#ea580c',
      '#dc2626',
      '#c026d3',
      '#7c3aed',
      '#475569',
    ],
    scopeOptions: [
      { value: 'public', label: '所有人' },
      { value: 'members', label: '已登录用户' },
      { value: 'staff', label: '仅管理员' },
    ],
    iconOptions: [
      { value: 'fas fa-comments', label: '讨论' },
      { value: 'fas fa-comment-dots', label: '对话' },
      { value: 'fas fa-code', label: '代码' },
      { value: 'fas fa-terminal', label: '终端' },
      { value: 'fas fa-bug', label: '问题' },
      { value: 'fas fa-lightbulb', label: '想法' },
      { value: 'fas fa-rocket', label: '发布' },
      { value: 'fas fa-book', label: '文档' },
      { value: 'fas fa-graduation-cap', label: '教程' },
      { value: 'fas fa-wrench', label: '工具' },
      { value: 'fas fa-cubes', label: '框架' },
      { value: 'fas fa-plug', label: '插件' },
      { value: 'fas fa-cloud', label: '云服务' },
      { value: 'fas fa-server', label: '服务端' },
      { value: 'fas fa-database', label: '数据库' },
      { value: 'fas fa-shield-alt', label: '安全' },
      { value: 'fas fa-mobile-alt', label: '移动端' },
      { value: 'fas fa-desktop', label: '桌面端' },
      { value: 'fas fa-image', label: '图片' },
      { value: 'fas fa-video', label: '视频' },
      { value: 'fas fa-music', label: '音频' },
      { value: 'fas fa-gamepad', label: '游戏' },
      { value: 'fas fa-briefcase', label: '工作' },
      { value: 'fas fa-chart-line', label: '增长' },
      { value: 'fas fa-bullhorn', label: '公告' },
      { value: 'fas fa-fire', label: '热门' },
      { value: 'fas fa-star', label: '精选' },
      { value: 'fas fa-heart', label: '喜欢' },
      { value: 'fas fa-users', label: '社区' },
      { value: 'fas fa-user-shield', label: '管理' },
      { value: 'fas fa-tags', label: '标签' },
      { value: 'fas fa-thumbtack', label: '置顶' },
      { value: 'fas fa-lock', label: '锁定' },
      { value: 'fas fa-language', label: '语言' },
      { value: 'fas fa-globe', label: '全球' },
      { value: 'fas fa-seedling', label: '新手' },
    ],
  }),
})
    .pageActionMeta(PAGE_KEY, {
  key: 'tags-page-actions-meta',
  order: 10,
  resolve: () => ({
    loadErrorText: '加载标签失败，请稍后重试',
    saveIncompleteTitle: '信息不完整',
    saveIncompleteMessage: '请输入标签名称',
    saveFailedTitle: '保存失败',
    saveUnknownErrorText: '未知错误',
    deleteConfirmTitle: '删除标签',
    deleteConfirmMessage: tag => `确定要删除标签“${tag}”吗？`,
    deleteConfirmText: '删除',
    deleteCancelText: '取消',
    deleteSuccessTitle: '标签已删除',
    deleteSuccessMessage: tag => `标签“${tag}”已删除。`,
    deleteFailedTitle: '删除失败',
    deleteFailedMessage: '未知错误',
    refreshConfirmTitle: '刷新标签统计',
    refreshConfirmMessage: '确定刷新全部标签的讨论数和最后发帖信息吗？数据量较大时建议在低峰期执行。',
    refreshConfirmText: '刷新',
    refreshCancelText: '取消',
    refreshFailedTitle: '刷新标签统计失败',
    refreshFailedMessage: '未知错误',
    moveFailedTitle: '调整排序失败',
    moveFailedMessage: '未知错误',
  }),
}))
}
