# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_access_scopes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tag",
            name="tags_slug_c72f9b_idx",
        ),
        migrations.RemoveIndex(
            model_name="tag",
            name="tags_positio_894349_idx",
        ),
        migrations.AlterField(
            model_name="tag",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
