# Generated by Codex on 2026-06-28

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_remove_tag_tags_slug_c72f9b_idx_and_more"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marked_as_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="tags.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_states",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tag_user",
            },
        ),
        migrations.AddIndex(
            model_name="tagstate",
            index=models.Index(fields=["user"], name="tag_user_user_id_0f20f5_idx"),
        ),
        migrations.AddIndex(
            model_name="tagstate",
            index=models.Index(fields=["tag"], name="tag_user_tag_id_8e3d59_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tagstate",
            unique_together={("user", "tag")},
        ),
    ]
